# Generated by Django 3.1.7 on 2021-03-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('service_type', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
            ],
            options={
                'ordering': ['date', 'service_type'],
                'unique_together': {('date', 'service_type')},
            },
        ),
    ]
